version: "3.5"
services:
  orion-explorer:
    image: marcdespland/orion-explorer
    container_name: orion-explorer
    hostname: orionexplorer
    ports:
      - "80:80"
    environment:
      - VUE_APP_CLIENT_ID=f69feb5c-5d9c-4103-a33a-3c7bc926e35d
      - VUE_APP_REDIRECT_URI=http%3A%2F%2F172.17.0.1:8080
      - VUE_APP_ORION_URL=http://192.168.1.32:8091
      - VUE_APP_ORION_SERVICE=PIXEL
      - VUE_APP_ORION_SERVICE_PATH=/FRBOD
      - VUE_APP_OAUTH_URL=http://192.168.1.32:3000  